name = "url-shortener"
compatibility_date = "2024-09-19"
compatibility_flags = ["experimental", "kv_direct_binding", "nodejs_compat"]

routes = [{ pattern = "rbsttr.tv", custom_domain = true }]

[[kv_namespaces]]
binding = "URLS"
id = "fde811d23bd544a8ad15f3b6a2166d8c"

# Pre-release
[observability]
enabled = true
