name = "url-shortener"
compatibility_date = "2024-09-27"
compatibility_flags = [ "nodejs_compat" ]

routes = [{ pattern = "rbsttr.tv", custom_domain = true }]

[[kv_namespaces]]
binding = "URLS"
id = "9b0e7e5dacb14591a4aa7b1d34ad432e" # Beta
# id = "fde811d23bd544a8ad15f3b6a2166d8c" # Old

# Pre-release
[observability]
enabled = true
