name = "url-shortener"
compatibility_date = "2025-08-21"

routes = [{ pattern = "rbsttr.tv", custom_domain = true }]

[[kv_namespaces]]
binding = "URLS"
id = "fde811d23bd544a8ad15f3b6a2166d8c"

[observability]
enabled = true
