name = "url-shortener"
main = "src/worker.ts"
compatibility_date = "2024-01-12"
compatibility_flags = [ "nodejs_compat" ]

# Send telemetry to Baselime via Tail Worker
tail_consumers = [{service = "url-shortener-tail"}]

routes = [
    { pattern = "rbsttr.tv", custom_domain = true }
]

# KV Namespace binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/kv
[[kv_namespaces]]
binding = "URLS"
id = "fde811d23bd544a8ad15f3b6a2166d8c"

[vars]
SERVICE_NAME = "url-shortener"
